### ISSUE TITLE
[Client] [FEAT] Client 개발 환경 셋팅

### ISSUE THREAD

**Issue by jhsung23** [codestates-seb/seb44_pre_037#29]
## 요구사항 ID
SET-001

## 요구사항
Client 개발 환경 셋팅

## 상세 요구사항
Client 애플리케이션 개발을 위한 개발 환경 셋팅

## TODO
- [x] vite로 react app
- [x] 기초 라우팅 작업
- [x] 폴더 구조 정하기 (4단계)
- [x] 라이브러리 논의
- [x] 스타일
